project:
  type: website
  resources: 
    - cv.pdf
    
website:
  title: "Johannes Ingrisch"
  page-footer: 
    center: |
      Copyright 2023 Johannes Ingrisch
  twitter-card: 
    card-style: summary_large_image
    creator: "@JohnnyIngrisch"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.qmd
#      - text: Blog
#        file: blog.qmd
#      - text: CV
#        file: cv.qmd
#      - text: Research
#        file: science.qmd
      - text: Publications
        file: publications.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/JohnnyIngrisch
      - icon: envelope
        href: mailto:johannes.ingrisch@posteo.net
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    self-contained: true
    link-external-newwindow: true
cookie-consent: 
  type: express
  style: headline
  palette: dark
editor: visual

